services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    environment:
      APP_ENV: dev
      APP_SECRET: "26cc1c3289d954da9718edba701e69a884e9929019afe2fd741638c37374874d"
    command: php -S 0.0.0.0:8000 -t public
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:16
    container_name: epicafe-database
    environment:
      POSTGRES_DB: epicafe
      POSTGRES_USER: epicafe
      POSTGRES_PASSWORD: epicafe
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "epicafe", "-U", "epicafe"]
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - epicafe_db_data:/var/lib/postgresql/data

volumes:
  epicafe_db_data:
