<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260225105539 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE partner (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(180) NOT NULL, slug VARCHAR(220) NOT NULL, website_url VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, bullet1 VARCHAR(255) DEFAULT NULL, bullet2 VARCHAR(255) DEFAULT NULL, bullet3 VARCHAR(255) DEFAULT NULL, logo_file_name VARCHAR(255) DEFAULT NULL, logo_url VARCHAR(255) DEFAULT NULL, position SMALLINT DEFAULT 0 NOT NULL, is_published BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_312B3E16989D9B62 ON partner (slug)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE partner');
    }
}
