<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Suppression des tables category et page : entités générées par make:entity
 * au tout début du projet, jamais utilisées (aucune relation, aucun rendu côté
 * site, CRUD vides). Vérifié avant suppression : 0 ligne dans les deux tables.
 */
final class Version20260814101500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Drop unused category and page tables (dead scaffolding).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS category');
        $this->addSql('DROP TABLE IF EXISTS page');
    }

    public function down(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE category (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                name VARCHAR(255) NOT NULL,
                slug VARCHAR(255) NOT NULL,
                "position" INT NOT NULL,
                is_active BOOLEAN NOT NULL,
                PRIMARY KEY(id)
            )
        SQL);

        $this->addSql(<<<'SQL'
            CREATE TABLE page (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                title VARCHAR(255) NOT NULL,
                slug VARCHAR(255) NOT NULL,
                content TEXT DEFAULT NULL,
                "position" INT NOT NULL,
                is_active BOOLEAN NOT NULL,
                PRIMARY KEY(id)
            )
        SQL);

        $this->addSql('CREATE UNIQUE INDEX UNIQ_140AB620989D9B62 ON page (slug)');
    }
}
