<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Création de la table shop_category (catégories de la page Boutique).
 */
final class Version20260424125921 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create shop_category table for editable shop page sections.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE shop_category (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                name VARCHAR(160) NOT NULL,
                slug VARCHAR(180) NOT NULL,
                kicker VARCHAR(120) DEFAULT NULL,
                description TEXT DEFAULT NULL,
                icon VARCHAR(10) DEFAULT NULL,
                image_file_name VARCHAR(255) DEFAULT NULL,
                "position" SMALLINT DEFAULT 0 NOT NULL,
                is_published BOOLEAN DEFAULT true NOT NULL,
                created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_shop_category_slug ON shop_category (slug)');
        $this->addSql('COMMENT ON COLUMN shop_category.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN shop_category.updated_at IS \'(DC2Type:datetime_immutable)\'');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE shop_category');
    }
}
