<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260303090148 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE menu_category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, slug VARCHAR(120) NOT NULL, position INT DEFAULT 0 NOT NULL, is_published BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2A1D5C57989D9B62 ON menu_category (slug)');
        $this->addSql('CREATE TABLE menu_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(160) NOT NULL, description TEXT DEFAULT NULL, unit VARCHAR(40) DEFAULT NULL, price NUMERIC(10, 2) DEFAULT NULL, position INT DEFAULT 0 NOT NULL, is_published BOOLEAN DEFAULT true NOT NULL, category_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D754D55012469DE2 ON menu_item (category_id)');
        $this->addSql('CREATE TABLE menu_item_variant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label VARCHAR(80) NOT NULL, price NUMERIC(10, 2) NOT NULL, position INT DEFAULT 0 NOT NULL, item_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_851C685C126F525E ON menu_item_variant (item_id)');
        $this->addSql('ALTER TABLE menu_item ADD CONSTRAINT FK_D754D55012469DE2 FOREIGN KEY (category_id) REFERENCES menu_category (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE menu_item_variant ADD CONSTRAINT FK_851C685C126F525E FOREIGN KEY (item_id) REFERENCES menu_item (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE partner ALTER type DROP DEFAULT');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE menu_item DROP CONSTRAINT FK_D754D55012469DE2');
        $this->addSql('ALTER TABLE menu_item_variant DROP CONSTRAINT FK_851C685C126F525E');
        $this->addSql('DROP TABLE menu_category');
        $this->addSql('DROP TABLE menu_item');
        $this->addSql('DROP TABLE menu_item_variant');
        $this->addSql('ALTER TABLE partner ALTER type SET DEFAULT \'partner\'');
    }
}
