<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260317152104 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE event_block DROP CONSTRAINT fk_c200260e71f7e88b');
        $this->addSql('DROP TABLE event_block');
        $this->addSql('ALTER TABLE event ADD offer_type VARCHAR(20) DEFAULT \'menu\' NOT NULL');
        $this->addSql('ALTER TABLE event ADD product1_name VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE event ADD product1_ingredients TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE event ADD product1_price NUMERIC(10, 2) DEFAULT NULL');
        $this->addSql('ALTER TABLE event ADD product2_name VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE event ADD product2_ingredients TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE event ADD product2_price NUMERIC(10, 2) DEFAULT NULL');
        $this->addSql('ALTER TABLE event ADD product3_name VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE event ADD product3_ingredients TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE event ADD product3_price NUMERIC(10, 2) DEFAULT NULL');
        $this->addSql('ALTER TABLE event ADD side_dish TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE event ADD offer_note TEXT DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE event_block (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(30) NOT NULL, title VARCHAR(255) DEFAULT NULL, starter VARCHAR(255) DEFAULT NULL, main VARCHAR(255) DEFAULT NULL, dessert1 VARCHAR(255) DEFAULT NULL, dessert2 VARCHAR(255) DEFAULT NULL, ingredients TEXT DEFAULT NULL, details TEXT DEFAULT NULL, price NUMERIC(10, 2) DEFAULT NULL, "position" INT NOT NULL, event_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_c200260e71f7e88b ON event_block (event_id)');
        $this->addSql('ALTER TABLE event_block ADD CONSTRAINT fk_c200260e71f7e88b FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE event DROP offer_type');
        $this->addSql('ALTER TABLE event DROP product1_name');
        $this->addSql('ALTER TABLE event DROP product1_ingredients');
        $this->addSql('ALTER TABLE event DROP product1_price');
        $this->addSql('ALTER TABLE event DROP product2_name');
        $this->addSql('ALTER TABLE event DROP product2_ingredients');
        $this->addSql('ALTER TABLE event DROP product2_price');
        $this->addSql('ALTER TABLE event DROP product3_name');
        $this->addSql('ALTER TABLE event DROP product3_ingredients');
        $this->addSql('ALTER TABLE event DROP product3_price');
        $this->addSql('ALTER TABLE event DROP side_dish');
        $this->addSql('ALTER TABLE event DROP offer_note');
    }
}
