<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Création de la table site_setting (paramètres globaux du site).
 */
final class Version20260428090544 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create site_setting table for global editable site settings.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE site_setting (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                "key" VARCHAR(80) NOT NULL,
                label VARCHAR(180) NOT NULL,
                description TEXT DEFAULT NULL,
                value TEXT DEFAULT NULL,
                type VARCHAR(20) NOT NULL,
                group_name VARCHAR(40) NOT NULL,
                "position" SMALLINT DEFAULT 0 NOT NULL,
                updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_site_setting_key ON site_setting ("key")');
        $this->addSql('COMMENT ON COLUMN site_setting.updated_at IS \'(DC2Type:datetime_immutable)\'');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE site_setting');
    }
}
