<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260317143606 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE event_block (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(30) NOT NULL, title VARCHAR(255) DEFAULT NULL, starter VARCHAR(255) DEFAULT NULL, main VARCHAR(255) DEFAULT NULL, dessert1 VARCHAR(255) DEFAULT NULL, dessert2 VARCHAR(255) DEFAULT NULL, ingredients TEXT DEFAULT NULL, details TEXT DEFAULT NULL, price NUMERIC(10, 2) DEFAULT NULL, position INT NOT NULL, event_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C200260E71F7E88B ON event_block (event_id)');
        $this->addSql('ALTER TABLE event_block ADD CONSTRAINT FK_C200260E71F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE event_block DROP CONSTRAINT FK_C200260E71F7E88B');
        $this->addSql('DROP TABLE event_block');
    }
}
