<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Création de la table google_review (avis affichés dans le carousel).
 */
final class Version20260428094237 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create google_review table for the customer reviews carousel.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE google_review (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                author VARCHAR(120) NOT NULL,
                rating SMALLINT DEFAULT 5 NOT NULL,
                text TEXT NOT NULL,
                review_date DATE DEFAULT NULL,
                is_published BOOLEAN DEFAULT true NOT NULL,
                "position" SMALLINT DEFAULT 0 NOT NULL,
                created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('COMMENT ON COLUMN google_review.review_date IS \'(DC2Type:date_immutable)\'');
        $this->addSql('COMMENT ON COLUMN google_review.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN google_review.updated_at IS \'(DC2Type:datetime_immutable)\'');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE google_review');
    }
}
