<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Création de la table site_image (emplacements d'images éditables du site).
 */
final class Version20260424123752 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create site_image table for editable site banners/photos.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE site_image (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                slug VARCHAR(80) NOT NULL,
                label VARCHAR(180) NOT NULL,
                description TEXT DEFAULT NULL,
                file_name VARCHAR(255) DEFAULT NULL,
                fallback_path VARCHAR(255) DEFAULT NULL,
                updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_site_image_slug ON site_image (slug)');
        $this->addSql('COMMENT ON COLUMN site_image.updated_at IS \'(DC2Type:datetime_immutable)\'');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE site_image');
    }
}
